SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `BOOK`;
DROP TABLE IF EXISTS `LOGHISTORY`;
DROP TABLE IF EXISTS `READHISTORY`;
DROP TABLE IF EXISTS `RECOMMANDBOOK`;
DROP TABLE IF EXISTS `GROUP`;
DROP TABLE IF EXISTS `SETTING`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `USER` (
	`USER_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`USER_TYPE` VARCHAR(1) NOT NULL,
	`USER_ID` VARCHAR(20) NOT NULL,
	`GRUP_CD` VARCHAR(20) NOT NULL,
	`USER_NM` VARCHAR(20) NOT NULL,
	`USER_PW` VARCHAR(20) NOT NULL,
	`USER_ALLOW_FLAG` VARCHAR(1) NOT NULL,
	`USER_AUTH_ST_DATE` VARCHAR(8) NOT NULL,
	`USER_AUTH_ED_DATE` VARCHAR(8) NOT NULL,
	`USER_PW_RESET_DATE` VARCHAR(8) NOT NULL,
	`C_DT` VARCHAR(12) NOT NULL,
	`C_ID` VARCHAR(20) NOT NULL,
	`U_DT` VARCHAR(12) NOT NULL,
	`U_ID` VARCHAR(20) NOT NULL,
	`DTL_FLAG` VARCHAR(1) NOT NULL,
	PRIMARY KEY (`USER_NO`),
	UNIQUE (`USER_ID`)
);

CREATE TABLE `BOOK` (
	`BOOK_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`BOOK_CD` VARCHAR(20) NOT NULL,
	`BOOK_ISBN` VARCHAR(13) NOT NULL,
	`BOOK_CLASS` VARCHAR(20) NOT NULL,
	`BOOK_NM` VARCHAR(20) NOT NULL,
	`BOOK_SUB_NM` VARCHAR(20),
	`BOOK_AUTHOR` VARCHAR(20),
	`BOOK_PUBLISHER` VARCHAR(20),
	`BOOK_PATH` VARCHAR(255) NOT NULL,
	`BOOK_PUB_DATE` VARCHAR(8),
	`BOOK_REG_DATE` VARCHAR(8) NOT NULL,
	`RECO_CODE` VARCHAR(20),
	`C_DT` VARCHAR(12) NOT NULL,
	`C_ID` VARCHAR(20) NOT NULL,
	`U_DT` VARCHAR(12) NOT NULL,
	`U_ID` VARCHAR(20) NOT NULL,
	`DTL_FLAG` VARCHAR(1) NOT NULL,
	PRIMARY KEY (`BOOK_NO`),
	UNIQUE (`BOOK_CD`)
);

CREATE TABLE `LOGHISTORY` (
	`LOG_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(20) NOT NULL,
	`LOG_IN_DT` VARCHAR(12) NOT NULL,
	`LOG_OUT_DT` VARCHAR(12),
	PRIMARY KEY (`LOG_NO`)
);

CREATE TABLE `READHISTORY` (
	`HIS_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`BOOK_CD` VARCHAR(20) NOT NULL,
	`C_DT` VARCHAR(12) NOT NULL,
	`C_ID` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`HIS_NO`)
);

CREATE TABLE `RECOMMANDBOOK` (
	`RECO_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`RECO_CD` VARCHAR(20) NOT NULL,
	`RECO_NM` VARCHAR(20) NOT NULL,
	`C_DT` VARCHAR(12) NOT NULL,
	`C_ID` VARCHAR(20) NOT NULL,
	`U_DT` VARCHAR(12) NOT NULL,
	`U_ID` VARCHAR(20) NOT NULL,
	`DTL_FLAG` VARCHAR(1) NOT NULL,
	PRIMARY KEY (`RECO_NO`)
);

CREATE TABLE `GROUP` (
	`GRUP_NO` INTEGER NOT NULL AUTO_INCREMENT,
	`GRUP_CD` VARCHAR(20) NOT NULL,
	`GRUP_NM` VARCHAR(20) NOT NULL,
	`GRUP_ALLOW_FLAG` VARCHAR(1) NOT NULL,
	`C_DT` VARCHAR(12) NOT NULL,
	`C_ID` VARCHAR(20) NOT NULL,
	`U_DT` VARCHAR(12) NOT NULL,
	`U_ID` VARCHAR(20) NOT NULL,
	`DTL_FLAG` VARCHAR(1) NOT NULL,
	PRIMARY KEY (`GRUP_NO`)
);

CREATE TABLE `SETTING` (
	`SETT_AUTO_ED_MIN` VARCHAR(5) NOT NULL,
	`SETT_PW_CYCLE` VARCHAR(5) NOT NULL,
	`U_DT` VARCHAR(12) NOT NULL,
	`U_ID` VARCHAR(20) NOT NULL
);
